### ISSUE TITLE
Trouble adding family characteristic columns

### ISSUE THREAD

**Issue by dpek96** [arcenis-r/cepumd#7]
Thank you for the wonderful code! It has really helped me learn how to leverage the CES data way more than the example code they post. 

I'm using ```ce_prepdata()``` to pull in info across expenditure categories. I'm interested in a very particular subset, based on age, education, and family size. AGE_REF & FAM_SIZE I have no issues specifying as a family characteristic. However, EDUC_REF is not able to be added to family characteristics. 

Tracing back the error, it has to do with how the data is being read in within ```read.fmli()```  function. EDUC_REF is read in as a character for all files except one, where it is a double. When ```dplyr::bind_rows()``` is called it won't combine b/c of the differing variable type.

**Comment by arcenis-r** [comment]
I'm very sorry for my delayed response here. I just started doing some maintenance on this package again after a while. Also, thank you for tracing that issue to it's possible source. I'll take a look and try to fix it in the next day or two. Are you able to tell me what years you worked with? Also, since you looked into "read.fmli" can I assume that you're working with just Interview data or are you performing an analysis with integrated data?
